### ISSUE TITLE
Getting AUTO_INCREMENT value on persist();

### ISSUE THREAD

**Issue by anton-johansson** [speedment/speedment#105]
If I'd have a primary key column with AUTO_INCREMENT, it would be very nice to get the generated value when I use ```#persist()```.

Would it be possible for Speedment to execute ```LAST_INSERT_ID();``` for example, to get the generated value? I guess we would have to make sure that this works the same for all DBMS-implementations (all that support some kind of AUTO_INCREMENT or auto-generation).

Example:
```java
Hare dbHarry = hares.newInstance()
    .setName("Harry")
    .setColor("Gray")
    .setAge(3)
    .persist();

System.out.println(dbHarry.getHareId());
// -> 1
```

Alternatively get it in the persist-metadata somehow:
```java
    .persist(m -> System.out.println(m.getLastInsertId()));
```
... but it feels a little tedious.

**Comment by Pyknic** [comment]
It should be like that already so if it doesn't work then that is a bug. I think that it the kind of thing our tests should have caught. We'll look into that!

**Comment by anton-johansson** [comment]
Hmm, strange... I'm pretty sure I didn't get my ID's set when I tried (I tried yesterday, submitted issue today). But maybe I did something wrong. Let me double check before investigating further.

**Comment by Pyknic** [comment]
Hello! Have you been able to reproduce this? I was wondering if we need to fix it for the Hamilton release.

**Comment by anton-johansson** [comment]
Haven't had the time to work on that project. But let me check when I get home from work, in maybe an hour or so.

**Comment by anton-johansson** [comment]
Not really sure where I got this from, must've seen completely wrong. Works perfectly. I'm sorry for wasted time.

**Comment by Pyknic** [comment]
No problem! Just glad it works!
