### ISSUE TITLE
Move UI into separate project

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#116]
This is a big change, but the code base for Speedment now consists of over 700 java files and many of them are related to the UI tool. For the future stability of the project it would be good to convert the project into a multi-module project where the UI is an optional module. That way we could have the `core` and `api` packages available for everyone but limit visibility of the UI to those that want to use it.

Suggestion on how we could separate packages into modules:
- core (`annotation`, `code`, `component`, `config`, `core`, `db`, `exception`, `field`, `logging`, `util`, `stream`)
- codegen (`codegen`, `core.code`, some of the components)
- ui (`ui`, some of the components)

`ui` depend on `codegen`, `codegen` depend on `core`. A production project only need to depend on `core`.

**Comment by anton-johansson** [comment]
Sounds like very good changes!

**Comment by Pyknic** [comment]
This is a duplicate of #100.
