### ISSUE TITLE
Auto-increment columns fails for Postgres

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#120]
Description; I tried inserting new objects into a table with an auto-increment primary key through the generated code. Even when I flagged that field as an auto-incremented field within the GUI, the code attempted to insert a null value into that field, which of course caused Postgres to throw an error. 

Solution: If a field is marked as auto-increment and the corresponding value is null, then that field shall not be present in .persist()'s column list at all.

**Comment by bitsofalex** [comment]
+1
