### ISSUE TITLE
No Provision to modify properties of the Connection Url like useSSL=false

### ISSUE THREAD

**Issue by arunt4ever** [speedment/speedment#131]

**Comment by Pyknic** [comment]
This is a good suggestion! You can override many of the properties like password, ip-adress and port in the application main-method by calling `withXXX()` before building the application into a `Speedment` instance, but right now you can't modify the actual connection object.

**Comment by Pyknic** [comment]
This will be available in the 2.3.0 Hamilton release. If you want to check it out earlier you can try the `develop` branch.
