### ISSUE TITLE
Maximized/Windowed UI settings should be saved between sessions

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#133]
A small cause of frustration when working with the UI is that the maximized/windowed mode is not saved. If you prefer to work in full screen and your screen size makes windowed mode the default, it will always open in window the default. If the user makes the app maximized once, it should always open as maximized. This could be done by looking at how we save the email address in the system properties.

**Comment by sergiofigueras** [comment]
Can you assign that for me, Pyknic?
