### ISSUE TITLE
Build error on classes generated with references to String field Foreign Key

### ISSUE THREAD

**Issue by bganesan** [speedment/speedment#136]
I have a table with type 'char' as the primary key. There are other tables that refer to this as foreign key. Speedment successfully generates the code but the classes that refer to this primary key field has build errors.

@Override
public Optional<A> findByStringKey() {
        return getStringKey()
            .flatMap(stringKey_ -> managerOf_(StringKey.class).findAny(<StringField>, stringKey_));
}

The error is in the findAny method which always expects a ComparableField.

How could this be handled? Its tough for me to change the type of the field but I believe there are valid use cases to use string primary key.

**Comment by minborg** [comment]
Could you please post how the table looks like (DDL) and also one table that referres to this table.

**Comment by bganesan** [comment]
Here are the table details.

Table: FULFILLMENT_NAME (table with CHAR primary key)		
		
Field	                                        Type	      Key
FULFILLMENT_NAME	                char(6)	      PRI
FULFILLMENT_DESCRIPTION	varchar(128)	
LAST_UPDATED_TS	                timestamp      MUL
CREATED_TS	                        timestamp	


Table: FULFILLMENT_METHOD(table has the foreign key reference; FULFILLMENT_NAME_ID is the foreign key reference)			
			
Field	                                   Type	     Key
FULFILLMENT_METHOD_ID    int(11)	     PRI	
FULFILLMENT_NAME_ID	   char(6)	     MUL	
LAST_UPDATED_TS	           timestamp  MUL	
CREATED_TS	                   timestamp

**Comment by minborg** [comment]
Fixed in develop branch.
