### ISSUE TITLE
Add TypeMapper from Integer types to Boolean

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#138]
It would be good if you could map from integer types like INT and TINYINT to boolean using a default type mapper. They shouldn't be very difficult to create and it is therefore a good issue if any first-time committer wants to start constributing to the project.

**Comment by robertsv** [comment]
@Pyknic - Can you assign this issue on me, so that I can start work on it!

**Comment by minborg** [comment]
@robertsv - Any progress on this issue? We are planning to release shortly and would like to include this issue in the next release.

**Comment by robertsv** [comment]
@minborg - Honestly I haven't had a change to take a look. As I understand then idea is to have a mapper similar as  "YesNoStringToBooleanMapper" ...

**Comment by minborg** [comment]
Yeah. That is right, and there can be several mappers too. From integer, short and byte to boolean for example. But no worries, we will move this issue to the next release so you still have plenty of time...

**Comment by robertsv** [comment]
@minborg - Is there a guide how to build speedment from source?

**Comment by minborg** [comment]
@robertsv One can build it directly in the IDE. We mostly use NetBeans but you can use any IDE like IDEA for example. Clone speedment/speedment and speedment/speedment-maven-plugin. Make sure you are on the 'develop' branch. Then just clean and build and you are good to go...

**Comment by Timmeey** [comment]
If i understand it right, it would "just" be an implementation of
[TypeMapper.java](https://github.com/speedment/speedment/blob/develop/src/main/java/com/speedment/config/db/mapper/TypeMapper.java) with the types (for mysql) ``` extends TypeMapper<Integer,Boolean>``` correct?

**Comment by robertsv** [comment]
@minborg @Pyknic - How can I create a pull request? Push fails with 403
```
$ git push origin feature-138
remote: Permission to speedment/speedment.git denied to robertsv.
fatal: unable to access 'https://github.com/speedment/speedment/': The requested URL returned error: 403
```

**Comment by Timmeey** [comment]
You can't push to the speedment original repository.

You need to fork the speedment repo, and then push to forked repository. from there you can issue a pull request.

For Help look [here](https://yangsu.github.io/pull-request-tutorial/) [here](https://help.github.com/articles/using-pull-requests/) or [here](https://help.github.com/articles/creating-a-pull-request/)

**Comment by robertsv** [comment]
@minborg @Pyknic - Here is the pull request https://github.com/speedment/speedment/pull/218

**Comment by minborg** [comment]
@robertsv Big thanks! Looks nice!

**Comment by minborg** [comment]
Verified
