### ISSUE TITLE
Remove exposed private references in UserInterfaceComponent

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#153]
UserInterfaceComponent in com.speedment.component,  has 2,  private references [com.speedment.internal.logging, com.speedment.internal.ui]

It is a bit tricky do contain these classes. Making them public will drag along a number of other classes. Making them private will restrict the usage of the UserInterfaceComponent.

**Comment by Pyknic** [comment]
This has been fixed in the `3.0.0` version.
