### ISSUE TITLE
Implement speedment.findManager(HareManager.class)

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#154]
This is usable in case one wants the typed version of the manager. For example
```java
HareManager hares = speedment.findManager(HareManager.class);
```

**Comment by Pyknic** [comment]
This is already possible since the new `speedment.getOrThrow()` works with managers as well as components. The usage looks like this:
```java
final HareApplication app = new HareApplicationBuilder().build();
final HareManager manager = app.getOrThrow(HareManager.class);
```

Alternatively, if you want to check if a manager exists, you can use the `get()`-method.

```java
final Optional<HareManager> manager = app.get(HareManager.class);
```
