### ISSUE TITLE
Add support for transactions in Speedment

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#188]

**Comment by hsaltin** [comment]
Lite flummig beskrivning

**Comment by dreifeldt** [comment]
Tydligen GitHub själva som väljer denna text

Den 2016-04-22 kl. 08:56, skrev hsaltin:
> Lite flummig beskrivning
>
> > Apr 22, 2016 kl. 8:48 AM skrev Per-Åke Minborg 
> <notifications@github.com>:
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub 
> <https://github.com/speedment/speedment/issues/188>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/speedment/speedment/issues/188#issuecomment-213488642>
>

-- 

*
Carina Dreifeldt  | CEO
*carina@speedment.com
*US +*1 650 387 4069
*Skype: carinadreifeldt
speedment.com <http://www.speedment.com/>
*speedment.org <http://www.speedment.org>

**Comment by minborg** [comment]
Medvetet. Vi har funderingar på lite olika sätt att göra det. Vi vet 
inte heller om det skall vara en enterprise funktion eller en open-source

On 4/22/16 8:56 AM, hsaltin wrote:
> Lite flummig beskrivning
>
> > Apr 22, 2016 kl. 8:48 AM skrev Per-Åke Minborg 
> <notifications@github.com>:
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub 
> <https://github.com/speedment/speedment/issues/188>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/speedment/speedment/issues/188#issuecomment-213488642>
>

-- 

Fwd: Instruktion hur du får in din signatur
*
Per Minborg  | CTO
*minborg@speedment.com
*US +*1 650 353 6579
*Skype: minborg
IM: @PMinborg
speedment.com <http://www.speedment.com/>
*speedment.org <http://www.speedment.org>

**Comment by svenruppert** [comment]
+1

**Comment by Pyknic** [comment]
Here is some thoughts on how the API could look from the user perspective:

```java
TransactionComponent txs = speedment.get(TransactionComponent.class);

final int sender   = 1001;
final int recipant = 1002;
final int transferAmount = 50_00;

txs.transaction().submit(tx -> { // Returns CompletableFuture<Integer>
    
    final Manager<Account> accounts = tx.managerOf(Account.class);
    final Manager<AccountEvent> accountEvents = tx.managerOf(AccountEvent.class);
 
    final Account fromAccount = accounts.stream()
        .filter(Account.ID.equal(sender))
        .findAny().get();

    final int currentBalance = fromAccount.getBalance();
    if (currentBalance >= transferAmount) {
        
        final Account toAccount = accounts.stream()
            .filter(Account.ID.equal(recipant))
            .findAny().get();

        accountEvents.newInstance()
            .setFrom(sender)
            .setTo(recipant)
            .setAmount(transferAmount)
            .persist();

        // Request a new aggregated view from the database
        return accounts.stream()
            .filter(Account.ID.equal(sender))
            .findAny()
			.get().getBalance();

    } else {
        throw new InsufficientBalanceException(
            "Balance of " + currentBalance + 
            " USD is not enough to withdraw " + withdrawalAmount + 
            " USD."
        );
    }

}).handleAsync((res, ex) -> {
    if (ex == null) {
        showMessage("Transaction succeeded! Current balance is now " + res + " USD.");
    } else {
        showError("Could not transfer money.", ex);
    }
});
```

**Comment by minborg** [comment]
Added in https://github.com/speedment/speedment/commit/48a07b4691b04275995ec196a24d8123893f5ba0
