### ISSUE TITLE
java: code too large

### ISSUE THREAD

**Issue by hussainssabir** [speedment/speedment#193]
Compilation issue in the Generated<MyDatabasename>ApplicationMetadata class.

Tested on: 2.3.1
MySQL: 5.1.38
IDE: Intellij

**Comment by Pyknic** [comment]
We could fix this by separating the generated metadata initializer into multiple static methods. I don't think there is any max size for files in java, only the 64kb limit of methods.

**Comment by minborg** [comment]
Fixed now by dividing the init() method into smaller parts.

**Comment by minborg** [comment]
@hussainssabir Can you test if it works now for you by checking out the 'develop' branch of Speedment and build it?

**Comment by hussainssabir** [comment]
Great. Thanks. @minborg and @pyknic. I will try tomorrow and will update.

**Comment by minborg** [comment]
@hussainssabir 2.3.2 is out now with this issue fixed!
