### ISSUE TITLE
Join fetch

### ISSUE THREAD

**Issue by hfluz** [speedment/speedment#216]
I don't know if this is the place to ask this.

I didn't find anything about this in the available docs. I'd like to know if there's (or there'll be) any kind of support to return data from more than one table in the same query (like the JPA join fetch).

As far as I understood from the examples, we'd have to run multiple queries for each register from a related table.

**Comment by Pyknic** [comment]
JOINs are not currently supported, but it is definetly something we want Speedment to be able to do in future versions.
