### ISSUE TITLE
Translator method forEveryTable does not execute for every table

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#224]
The name of the `forEveryTable`, `forEverySchema` and similar methods in the `Translator.Builder` interface is misleading since the supplied code is not executed for every table under that document, only for the same or an ancestor document.

Take the following document tree:

```
projectA --+--> dbmsA
           |
           +--> dbmsB
```

If we call `forEveryDbms` on `projectA`, it will never execute. If we call `forEveryDbms` on `dbmsB`, it will execute exactly once. If we call `forEveryProject` on any of the documents, it will execute exactly once.

For the method to do what is expected, it should not only search the document ancestors for matching types but also children. In the case for calling `forEveryDbms` on `projectA`, it should execute two times, once for `dbmsA` and once for `dbmsB`.

**Comment by Pyknic** [comment]
The bug can probably be fixed by modifying the `build()` method of `DefaultJavaClassTranslator.java`.

**Comment by minborg** [comment]
Running forEachTable or forEachIndex on a Project builder fails (e.g using the Sakila DB)
