### ISSUE TITLE
JavaDoc not updated to 3.0.0-EA version on github

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#243]

**Comment by lawesson** [comment]
The problems seems to be that the javadocs for 3.0.0-EA indeed have not been released in the speedment component. As seen in [this search](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.speedment%22%20AND%20a%3A%22speedment%22) the speedment top level is now a pom only. Perhaps we shall start referring to [runtime](http://search.maven.org/#search%7Cga%7C1%7Ccom.speedment%20a%3A%22runtime%22) javadocs instead?
