### ISSUE TITLE
Add support for for DEFAULT values

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#257]
PROBLEM:  try to insert new row, with .newEmptyEntity() and set all required fields, leaving ones with DEFAULT 0/1/CURRENT_TIMESTAMP/whatever. However, Speedment still tries to define these fields as NULL which violates not-null constraint of course. 

Making this work the way it should implies keeping track of which members were ever set. So if a member was not set, it should not be mentioned in the INSERT or UPDATE statement. For example, a String field with a default database value of say “Adam” could be set to null in the user code and then it should actually be set to null explicitly. If the field was never set, it should not be mentioned in the INSERT statement and the database would set it to “Adam”. Figuring out the default value does not work in the general case, since variables like CURRENT_TIMESTAMP may be used.

**Comment by lawesson** [comment]
fixed by merged features/selective-persist https://github.com/speedment/speedment/commit/bceadd43e2f0d34aef7b1afd97a346dee2670f84
