### ISSUE TITLE
Problematic usage of app.configure()

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#266]
We must provide the concrete Manager class to configure it. For example, UserManager.class. Everywhere else, the Manager<ENTITY> notation can be used.

**Comment by minborg** [comment]
Remove
     <ENTITY> Manager<ENTITY> managerOf(Class<ENTITY> entityType);
 and always use the UserManager.class

**Comment by Pyknic** [comment]
The old behaviour can still be achieved using:
```java
Manager<User> users = app.getOrThrow(ManagerComponent.class).managerOf(User.class);
```
...so there is no point in having a separate method in `Speedment` called `managerOf`.
