### ISSUE TITLE
Tool v3.0.0 reporting a newer 3.0.0-EA2 being available

### ISSUE THREAD

**Issue by lawesson** [speedment/speedment#275]
Versions on github are sorted lexicographically in VersionComponentImpl by Comparator.reverseOrder(), meaning that version 3.0.0-EA2 is considered more modern than 3.0.0.

**Comment by Pyknic** [comment]
It is the same with maven central and javadoc.io. Most sites consider 3.0.0-EA2 to be > 3.0.0.
