### ISSUE TITLE
.equals and .equalsIgnoreCase in SQL does not match correctly

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#28]
The predicate builders for `.equals` and `.equalsIgnoreCase` does not generate correct SQL since the `=` operator in SQL is case insensitive for non-binary strings. The SQL generator must therefore compare the byte values for strings if the comparing should be case sensitive.

**Comment by minborg** [comment]
Will not produce erroneous results because the original filter is applied but would be nice to fix anyhow.
