### ISSUE TITLE
Tutorials and Framework problems

### ISSUE THREAD

**Issue by vip365** [speedment/speedment#280]
A lot of Tutorials's code are old, inconsistent with the new API(e.g., Tutorials4).
In addition, Is it possible to add tutorials that integrate with the popular framework(e.g., SpringMVC)?

**Comment by minborg** [comment]
Very relevant comments. Thanks for that! We are working on Spring Boot stuff and hopefully we will be able to share that soon.

**Comment by Pyknic** [comment]
Version 3 of Speedment is fairly easy to integrate with Spring. Here is an example of a Configuration file from one of my projects:
```java
@Configuration
public class AppConfig {
    private @Value("${dbms.username}") String username;
    private @Value("${dbms.password}") String password;
    private @Value("${dbms.schema}") String schema;

    @Bean
    public SalesinfoApplication getSalesinfoApplication() {
        return new SalesinfoApplicationBuilder()
            .withUsername(username)
            .withPassword(password)
            .withSchema(schema)
            .build();
    }

    // Individual managers
    @Bean
    public SalespersonManager getSalespersonManager(SalesinfoApplication app) {
        return app.getOrThrow(SalespersonManager.class);
    }
}
```

So when I need to use a manager in a SpringMVC Controller, I can now simply autowire it.
```java
private @Autowired SalespersonManager salespeople;
```

**Comment by lawesson** [comment]
Tutorial 4 updated to Speedment 3.0.1.

**Comment by minborg** [comment]
Added Spring example
