### ISSUE TITLE
Blobs and Clobs returned from a terminated stream are stale

### ISSUE THREAD

**Issue by lawesson** [speedment/speedment#288]
As pointed out [here](http://docs.oracle.com/javase/8/docs/api/java/sql/Blob.html), a "Blob object is valid for the duration of the transaction in which is was created" since it does not contain the data itself, but merely a pointer into the ResultSet. A Blob object returned from termination of a Speedment stream refers to a transaction that is closed and therefore blob.getBytes(...) will throw an exception indicating that the lob is closed.

**Comment by minborg** [comment]
Surprisingly, MySQL allows Blobs to be used outside a Stream.

**Comment by minborg** [comment]
I have added a Wiki for Blobs and Clobs https://github.com/speedment/speedment/wiki/Working-with-Blobs-and-Clobs
