### ISSUE TITLE
postgresql autoIncrement bug

### ISSUE THREAD

**Issue by fx8080** [speedment/speedment#289]
default value is aways set to 0;
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "folder_pkey"
  ：Key (id)=(0) already exists.: javax.faces.FacesException: #{folderView.save}: com.speedment.runtime.core.exception.SpeedmentException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "folder_pkey"

**Comment by minborg** [comment]
This is probably related to #257

**Comment by paxbit** [comment]
Hi minborg/Pyknic,

could you please leave a short statement on when you plan to release 3.0.2 Forest? It's overdue by a month and some issues which are essential to us (#289, #221, #257) are already up to half a year old. 
Those bugs are deal breakers as they concern basic database functionality. IMO they should be taken care of with priority.

paxbit

**Comment by minborg** [comment]
We will review the release plan. I agree that we should fix the issues you mention ASAP.

**Comment by minborg** [comment]
@paxbit Version 3.0.2 is out now with many bugfixes. Check out https://github.com/speedment/speedment/releases/tag/3.0.2
