### ISSUE TITLE
Support for H2

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#292]
Add support for H2 databases.

**Comment by knutwannheden** [comment]
What changes are required to support another database like H2? Is it only about extending the code generator? I am asking because I would like to know if it is feasible to extend Speedment to support a custom database. Apart from that I am also really looking forward to H2 support. Thanks!

**Comment by minborg** [comment]
Check out the development branch https://github.com/speedment/speedment/tree/develop-3.0/connector-parent and see how we are planning to do support for different databases in separate modules. I have created this module with the MySQL driver classes but I have renamed them to H2. @knutwannheden Maybe you can take a look at H2 support using these template classes? That would be awesome!
