### ISSUE TITLE
The postgresql throws an exception when the PRIMARY KEY is not type long.

### ISSUE THREAD

**Issue by fx8080** [speedment/speedment#293]
org.postgresql.util.PSQLException: Bad value for type long : xxxxxx

case at com.speedment.runtime.core.internal.db.AbstractDbmsOperationHandler.handleSqlStatement(AbstractDbmsOperationHandler.java:234)

the source code is:             
try (final ResultSet generatedKeys = ps.getGeneratedKeys()) {
                while (generatedKeys.next()) {
                    sqlStatement.addGeneratedKey(generatedKeys.getLong(1));
                }
            }
        }

**Comment by minborg** [comment]
Can you please post the table creation statements and it will be easier to reproduce the error.

**Comment by lawesson** [comment]
Reproduced with

```SQL
CREATE TABLE salesinfo.serialid
(
    id character varying(255) NOT NULL,
    email character varying(255),
    CONSTRAINT primarykey PRIMARY KEY (id)
)
```

and

```java
    @Test
    public void testInsert() { 
        serialIds.persist(new SerialidImpl().setId("foo").setEmail("mail"));
        Serialid item = serialIds.stream().findAny().orElseThrow(RuntimeException::new);
    }
```
