### ISSUE TITLE
[Question] How to make joins

### ISSUE THREAD

**Issue by Godlex** [speedment/speedment#301]
Is there a possibility to make joins using Speedment? 

The documentation says that there is no need for it and I can do it like that:

// Find the owner of the orange carrot
Optional<Hare> hare = carrots.stream()
    .filter(Carrot.NAME.equal("Orange"))
    .map(hares.finderBy(Carrot.OWNER))
    .findAny();"

But is it possible to do something like this? 

SELECT  *
FROM    Player p
WHERE   p.Name = 'Godlex'
AND     EXISTS (SELECT 1 FROM User u WHERE u.Name = p.VisibleName AND u.Public = true)

**Comment by minborg** [comment]
There is a join example [here] (https://github.com/speedment/speedment#join) and in your specific case you could do something like this:
```java
Stream<Player> result = players.stream()
    .filter(Player.NAME.equal("Godlex"))
    .filter(p -> users.stream()
        .filter(User.NAME.equal(p.getVisibleName))
        .filter(User.PUBLIC.equal(true))
        .findAny()
        .isPresent()
    );
```
