### ISSUE TITLE
Aborted connection in mysql (Got an error reading communication packets)

### ISSUE THREAD

**Issue by rsrini7** [speedment/speedment#302]
I am able to generate code using maven speedment:tool and getting error while accessing app main.

Aborted connection 4 to db: 'unconnected' user: 'root' host: 'localhost' (Got an error reading communication packets)

**Comment by minborg** [comment]
Do you have the complete stack trace from the error? Did you manage to make it work?

**Comment by rsrini7** [comment]
No stack trace @ code end. Learning annotation processor and as of now not able to make it workable. I am using Windows 10.

**Comment by Pyknic** [comment]
I think we need some more information to be able to help you. In what way are you using annotation processing? Do you have any code samples you can post here or on [Gist](https://gist.github.com/)?

**Comment by rsrini7** [comment]
Please find my complete netbeans code setup in "https://github.com/rsrini7/Myspeedment"
 Also, i used the mysql test_db "https://github.com/datacharmer/test_db"

Thanks in advance.

**Comment by minborg** [comment]
@rsrini7 I just released a new version of Speedment and I see that you have an RC candidate and an old version in your example. Please update to speedment 3.0.4 both for runtime dependency and plugin and try again please. Also, update to the latest MySQL driver 6.0.x

**Comment by rsrini7** [comment]
Works fine with latest version. Thanks and closing this issue.
speedment version: 3.0.5
mysql version: 6.0.6
