### ISSUE TITLE
Improve BackwardFinder interface

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#310]
The BackwardFinder interface is currently a bit bulky to use. Consider the following case:

We have a table named `User` and a table named `Image`. Every Image has a column called `uploader` that references a specific user. Given a stream of users, we want to get a stream of images uploaded by those users.

In the natural Java Stream API, we would write it like this:
```java
public Stream<Image> imagesByUsers(Stream<User> users) {
    return users.flatMap(user -> images.findBackwardsBy(Image.UPLOADER, user));
}
```

The problem with the above is that we can't analyze the lambda expression since it is only an abstract object. This is what the `BackwardFinder`-interface was created to solve. Using that, the method above looks like this:
```java
public Stream<Image> imagesByUsers(Stream<User> users) {
    return users.flatMap(Image.UPLOADER.backwardFinder(
        images.getTableIdentifier(), 
        images::stream
    ));
}
```

It can now be analyzed during runtime, but the API is a bit bulky. Instead we would like to write:
```java
public Stream<Image> imagesByUsers(Stream<User> users) {
    return users.flatMap(Image.UPLOADER.backwardFinder(images));
}
```

This requires us to add a new method to the `BackwardFinder`-api, but that also reveals another issue. `BackwardFinder` is part of the `runtime-field`artifact and manager is part of `runtime-core`. Manager has many reasons to depend on Field, so if we were to add a dependency in the opposite direction we would get a circular dependency. Not good.

I therefore suggest that we add a number of traits to the `runtime-field` module that specifies the methods we need from manager to implement the method. Consider the following:

```java
public interface HasFinder<ENTITY, FK_ENTITY> {
    ...
    BackwardFinder<FK_ENTITY, ENTITY> backwardFinder(
        TableIdentifier<ENTITY> identifier, 
        Supplier<Stream<ENTITY>> streamSupplier
    ); // The method as it looks today (version 3.0.2)

    default BackwardFinder<FK_ENTITY, ENTITY, 
        MANAGER extends HasTableIdentifier<ENTITY> & HasStream<ENTITY>
    > backwardFinder(MANAGER manager) { // Proposed method.
        return backwardFinder(manager.getTableIdentifier(), manager::stream);
    }
}
```

`HasTableidentifier` and `HasStream` would be new interface traits. We could also rename the current trait `HasIdentifier` to `HasColumnIdentifier` for case of consistency.

Thoughts about this change? I have proposed 3.1.0 as milestone since it will affect the API.

**Comment by minborg** [comment]
Joins can be used instead.
