### ISSUE TITLE
withSchema() does not work

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#336]
Because both Fields and the configuration model are using schema names that must match, it is not possible to change the schema name in the configuration model. Instead, we need to introduce a new Trait for the Schema name configuration and use that trait when rendering SQL commands.

**Comment by minborg** [comment]
We could introduce a new variable "dbName" that is being used when rendering SQL instead of the current "name". If no "dbName" is present, we could default to the existing "name".

**Comment by minborg** [comment]
Introduce an attribute called "id" that identifies a db entity. Name can then be changed to affect sql rendering. If no id, then use name. Identification must be done using "id" instead of name.

**Comment by minborg** [comment]
It will affect the SqlStreamSupplierImpl class amongst others

**Comment by Pyknic** [comment]
I personally prefer not to add things that make the config file more confusing (like a third `name` variant) but rather introduce a separate `id` attribute that only serves as the merging qualifier.

**Comment by minborg** [comment]
We should change 
```
public interface ColumnIdentifier<ENTITY> 
extends HasDbmsName,
        HasSchemaName,
        HasTableName,
        HasColumnName {

    default TableIdentifier<ENTITY> asTableIdentifier() {
        return TableIdentifier.of(getDbmsName(), getSchemaName(), getTableName());
    }

}
```

to 
```
public interface ColumnIdentifier<ENTITY> 
extends HasDbmsId,
        HasSchemaId,
        HasTableId,
        HasColumnId {

    default TableIdentifier<ENTITY> asTableIdentifier() {
        return TableIdentifier.of(getDbmsId(), getSchemaId(), getTableId());
    }

}
```
