### ISSUE TITLE
Maven Plugin command line params for typeMapers and components fails

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#380]
``` shell
mvn speedment:generate -DtypeMappers=com.so.MyTypeMapper,com.so.MyOtherTypeMapper
```
[ERROR] Failed to execute goal com.speedment:speedment-maven-plugin:3.0.6-SNAPSHOT:generate (default-cli) on project datastore-test: Unable to parse configuration of mojo com.speedment:speedment-maven-plugin:3.0.6-SNAPSHOT:generate for parameter #: Cannot find default setter in class com.speedment.maven.typemapper.Mapping -> [Help 1]

**Comment by lawesson** [comment]
Do we have any working example of type mapper being used and passed on the command line? I have pushed a very untested "fix" that I would like to further explore.

**Comment by minborg** [comment]
The user's guide section needs to be updated too! https://speedment.github.io/speedment-doc/maven.html#adding-a-type-mapper

**Comment by minborg** [comment]
Removed command line parameter for TypeMapper. Problem fixed
