### ISSUE TITLE
Postgresql db with SSL

### ISSUE THREAD

**Issue by smitalm** [speedment/speedment#392]
Hi, 

when trying to use speedment:tool to connect to my Heroku Postgresql DB, i am having exact same problem, as described [here](http://stackoverflow.com/questions/25641047/org-postgresql-util-psqlexception-fatal-no-pg-hba-conf-entry-for-host).

Is there any way that i can add `?sslmode=require` to the end of my DB connection URL?

**Comment by smitalm** [comment]
I just now found out, that adding the url params after DB name fixes my issue. Feel free to delete this issue :)

**Comment by Pyknic** [comment]
Hi! Adding it after the DB name is a bit of a hack and might not work in the future. If you want to future-proof your project, you can modify the `connectionUrl` in the `speedment.json`-file.

The option of configuring connection URL in the UI dialog has been requested before in #298 and is definitely something we plan to add the next time we do an UI overhaul.

Nice to see you found a solution, however!
