### ISSUE TITLE
Use resultSet.getInt(int ordinalColumn) instead of resultSet.getInt("columnName")

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#40]
will improve performance.

**Comment by Pyknic** [comment]
ResultSet is invoked by the generated manager implementation classes. To fix the issue the `EntityManagerImplTranslator` in `com.speedment.internal.core.code.manager` will be affected.

**Comment by orwashere** [comment]
Do you think implementing this is ok as it will break the code if someone changes the order of the columns in the database?
