### ISSUE TITLE
Use Collation for PostgreSQL

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#401]

**Comment by minborg** [comment]
This is related to #397 but for PostgreSQL

**Comment by lawesson** [comment]
PostgreSQL uses the collations of the OS and there is no way to use a specific collation for a specific query. 

Case insensitive comparisons can be achieved by using the ILIKE operator or regexp comparison using ~ or forcing both compared operands to lower case. The latter seems to be most efficient.

If modifying the database is an option, CITEXT fields can be used, but that is of course not a Speedment option.

Conclusion - using collation in Speedment queries is not an option. The best way seems to be the current implementation using LOWER(cn) = LOWER(?). I suggest we close this issue as won't fix.

See 
http://stackoverflow.com/questions/7005302/postgresql-how-to-make-case-insensitive-query
https://www.postgresql.org/docs/9.6/static/functions-matching.html
https://www.postgresql.org/docs/9.6/static/citext.html

**Comment by minborg** [comment]
Concur
