### ISSUE TITLE
Internal Classes cannot be get() from application

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#407]
Internal classes can be installed (e.g. using ```.withComponent()``` and will work as expected. However, it is not possible to ```.getOrThrow()``` them using their class.

Reproduce: Create a class that holds an inner static class. Inject the class in the SpeedmentBuilder. The class cannot be get:ed...

**Comment by Pyknic** [comment]
What exception is thrown?

**Comment by minborg** [comment]
Unable to reproduce:
```
public class MySqlOptimizeTest2 extends MySqlBaseTest {

    @Test
    public void olle() {
        MyClass c = app.getOrThrow(MyClass.class);
        System.out.println(c);
    }

    @Override
    protected SpeedmentTestApplicationBuilder configBuilder(SpeedmentTestApplicationBuilder builder) {
        return builder
            .withComponent(MyClass.class);
    }

    public static class MyClass {
    };

}

```
