### ISSUE TITLE
How to deal with crowded tables (a.k.a actual tables on production systems)

### ISSUE THREAD

**Issue by paxbit** [speedment/speedment#417]
This touches #400 #389 #413.

As far as I understand it there is currently no support in Speedment for:
* LIMITing the result set size by the dbms. It is always done in-memory by the JVM. 
* WHERE clauses containing OR linked expressions. They will also always be done in-memory.
* skipping (OFFSET) rows via SQL when using the workaround for OR queries described here: https://speedment.github.io/speedment-doc/predicate.html#or 

Now I've got an actual table currently containing 672807 rows. And I want to offer paging for its data grid on some frontend. I also want to offer a simple search capability where one entered term targets two OR linked fields in the table. I'm sure this has been done before.

With the current state of affairs in Speedment trying to implement this will:

1. when no search term was given:
* always fetch the whole table into JVM memory, then skip, then limit

2. when any search term was given:
* execute two queries, one for each term, then fully fetch both results
* compose both result sets using technique described here: https://speedment.github.io/speedment-doc/predicate.html#or
* again on the JVM side skip, then limit.

This is so utterly inefficient and slow that I cannot imagine I'm using Speedment (3.0.6) correctly. But OTOH I take my guidelines from here: https://speedment.github.io/speedment-doc

Some examples:

```
dataManager.stream()
  .sorted(...)                                     << performed by DBMS via SQL
  .skip(10L)                                     << performed by DBMS via SQL
  .limit(10L)                                     << performed by Java 
  .collect(Collectors.toList())
```
Runtimes
Plain SQL: 34ms
Speedment: ~6s

```
dataManager.stream()
  .filter(predicate1.or(predicate2))  << performed in-memory by Java
  .skip(10L)                                      << performed in-memory by Java
  .limit(10L)                                     << performed in-memory by Java 
  .collect(Collectors.toList())
```
Runtimes
Plain SQL: 34ms
Speedment: ~8s

```
StreamComposition.concatAndAutoClose(
  dataManager.stream().filter(predicate1),   << fully fetched, probably never reaches heap though
  dataManager.stream().filter(predicate2)    << fully fetched, probably never reaches heap though
)
.distinct()                                      << performed in-memory by Java 
.skip(offset)                                  << performed in-memory by Java 
.limit(pageSize)                            << performed in-memory by Java 
.collect(Collectors.toList());
```
Runtimes
Plain SQL: 34ms
Speedment: ~8s

We're not using Speedment in production yet. But if this turns out to be true I don't think we can.

**Comment by minborg** [comment]
We will take a look at these known issues ASAP.

**Comment by minborg** [comment]
#413 is fixed now in the develop branch. Will come in the next release.

**Comment by minborg** [comment]
#400 #389 fixed now

**Comment by minborg** [comment]
@paxbit It would be interesting to see what the performance is now that 3.0.7 is released.

**Comment by paxbit** [comment]
@minborg Thanks a lot. I'll have a look at it tomorrow.

**Comment by paxbit** [comment]
@minborg I did the tests again today. or(...), skip(...) and limit(...) are now rendered to SQL. The times for the Speedment execution time are now ~40ms, down from ~8s, compared to 34ms for manually retrieving the same data via query against the db. I think this is very good. Thank you for the quick changes!

There is another issue though which I just looked at - .count()

doing a
`manager.filter(...).count();`
too fetches everything from the table then counts the number of rows. This means that atm. I still cannot implement the paging feature because I need to tell the client the total number of rows over all pages.

There are probably more ways to deal with this. I can think of the following two:

1. Calling ...count() optimizes the query to:
`select count(*) from (select * from theTable where theConstraints) cnt;`
This is how i would expect it to work.

2. Offering a new method on the manager dedicated only to do optimized counting, like:
`manager.counting(predicate)`

Do you think any of this could be a viable option?

**Comment by minborg** [comment]
I have opened a new issue for this: #426

Alternative 1 should work. I will check what is wrong.

**Comment by minborg** [comment]
Version 3.0.8 is out now with optimized count() operations.
