### ISSUE TITLE
Codegen: Generics::asType does not take generics into account

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#436]
```
final Generic genericsOfT = Generic.of("?").setBoundType(SUPER).add(SimpleType.create("T"));
final Type t = genericsOfT.asType();
```
When `t` is rendered, only "?" will be in the generated code.

**Comment by Pyknic** [comment]
Hm, maybe the correct way to handle this would be to remove the method `asType()`? Generic variables are not always possible to convert into types. In the example above, is the type going to be `DefaultType.WILDCARD` or `T`?
