### ISSUE TITLE
Schema names that contains dots (.) does not work

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#44]
MySQL supports schema names with a dot in them [from version 5.1.6 and up](http://dev.mysql.com/doc/refman/5.1/en/identifiers.html), but Speedment can not handle them since a class name with a dot is not allowed in Java. A solution to this might be to replace dots with underscores in the generated code and escape the schema name in SQL queries.

**Comment by orwashere** [comment]
Underscores might not be sufficient as there may be databases with underscores in their names. A character should be found which is forbidden in the schema name.

**Comment by Pyknic** [comment]
Underscores in database names are currently turned into CamelCased names in java, so this shouldn't be a problem. If it does cause a name collision, the user can still choose a different name for the generated classes in the GUI.

**Comment by orwashere** [comment]
Makes sense. Thanks for the clarification.
