### ISSUE TITLE
Add static methods Entity.identifier()

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#454]
Currently the Fields have an `identifier()` method. For configuration issues, it would be good with a `Country::identifier` method for example. The CountryManager has a `tableIdentifier()` method but the managers are not available config time.

**Comment by Pyknic** [comment]
If a static method is added to the entity interface, then that would break our ambition to keep the interfaces and classes in the non-generated packages as placeholders. You could add an `IDENTIFIER` static field to the generated entity interface and then access it through the non-generated interface, but then it might collide with any field named `identifier`. Keeping it in the `Manager` interface is safer.

One possibility could be to generate a static `IDENTIFIER` member in the `GeneratedManager`-interface. It could then be accessed through the non-generated manager without risk of colliding with a field.

Example:
```java
// Entity fields:
Country.ID
Country.NAME

// Manager fields:
CountryManager.IDENTIFIER
```
