### ISSUE TITLE
Hidden Performance Problem with _CI Collation and BINARY

### ISSUE THREAD

**Issue by fablue** [speedment/speedment#475]
I noticed, that Speedment renders a sql statement using 
WHERE (BINARY ...) when .equal is used in conjunction with a _CI collation. 
I am not not very experienced with sql but my App currently suffers under HUGE performance problems and currently think, this might be the reason?

**Comment by Pyknic** [comment]
I don't think that this is an issue in the most recent version since we no longer generate queries with `WHERE BINARY`.
