### ISSUE TITLE
Expand/Collapse all for TreeNodes in GUI

### ISSUE THREAD

**Issue by Juchar** [speedment/speedment#48]
Minor convenience improvement: 

For large databases it is pretty tedious to collapse all the nodes in the tree view on the left side as they are expanded by default (e.g. to just have a quick look, quickly disable multiple tables from generation, etc,).

A right click action like e.g. "expand all" or "collapse all" would help.

**Comment by Pyknic** [comment]
I completely agree.

**Comment by Pyknic** [comment]
This is now fixed in develop-branch.
