### ISSUE TITLE
Runtime: ConnectionPoolComponent exposes unnescessary methods

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#488]
There are several methods in the `ConnectionPoolComponent` that doesn't need to be exposed in the API and that makes it more difficult to implement it. I suggest that we remove the following methods from the interface and make them private in the default implementation:

```java
PoolableConnection getConnection(String uri, String username, char[] password);
PoolableConnection newConnection(String uri, String username, char[] password);
```

**Comment by minborg** [comment]
These are now used
