### ISSUE TITLE
Optimize PredicateView

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#495]
Currently the PredicateView implementations render everything to SQL code, even AlwaysTrue and AlwaysFalse. Some of the predicates could be eliminated or short circuited. For example, ```AbstractFieldPredicateView::alwaysTrue``` and ```AbstractFieldPredicateView::alwaysFalse```. These predicates may imply a full table scan under some circumstances.

**Comment by lawesson** [comment]
The fix does not pass tests. For a pipeline with a single ALWAYS_TRUE filter, the generated SQL code will be `SELECT yadda, yadda, yadda FROM foo WHERE`.
