### ISSUE TITLE
Collations are not used in ORDER BY rendering

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#512]
Consider the following stream:
```
films.stream()
    .filter(FILM.RATING.equal(”PG-13”))
    .sorted(Film.TITLE.comparator())
```
Which will render to the following MySQL SQL statement:
```
 SELECT 
    `film_id`,`title`,`description`,`release_year`,
    `language_id`,`original_language_id`,`rental_duration`,`rental_rate`,
    `length`,`replacement_cost`,`rating`,`special_features`,
    `last_update` 
FROM 
    `sakila`.`film` 
WHERE
     (`sakila`.`film`.`rating`  = ? COLLATE utf8_bin) 
ORDER BY `sakila`.`film`.`title` ASC
```
This will produce a stream that is not ordered correctly since it does not ensure that the correct collation is used. So a film with the title "Alien" would be close to a film with the title "alien". The last part should instead be rendered to:

`ORDER BY `sakila`.`film`.`title` ASC  COLLATE utf8_bin;`

We should also introduce ignore case comparators like  `Film.TITLE.comparatorIgnoreCase()` to enable sorting in willful ignore case order.

**Comment by lawesson** [comment]
Actually, the last part should read

`ORDER BY sakila.film.title COLLATE utf8_bin ASC;`
