### ISSUE TITLE
Tuple: Rename Tuples.of(Object...) to Tuples.ofArray(Object...)

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#520]
Since `Object[]` inherits `Object`, it means that `Tuples.of(Object)` has the same signature as `Tuples.of(Object[])`. This causes problems since a method that returns a single `Object` can't be used with `Tuple.of()` without it wrapping the result in an array of dimension 1.

Example:
```java
Object foo() {
    return ...;
}

...

Tuple t = Tuples.of(foo()); // This will resolve to Tuples.of(Object[]), not Tuples.of(Object).
```

**Comment by minborg** [comment]
I suggest to rename the static constructor method to `Tuples.ofArray()`. This issue also affects `TupleOfNullable.of()`

**Comment by minborg** [comment]
We could check List.of() functions and see how that is handled in Java 9.

**Comment by minborg** [comment]
This will affect the API
