### ISSUE TITLE
Connect dialog fails

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#523]
If the user navigates between fields in the connect dialog, the values are not updated in the final connection string. Also, the settings.properties files might interfere with the values given by the user.

**Comment by minborg** [comment]
Might be related to #337

**Comment by Pyknic** [comment]
This is now potentially fixed by the removal of the settings.properties-file as described in #535.

**Comment by lawesson** [comment]
Verified to be fixed in 3.0.16
