### ISSUE TITLE
Runtime: Make PostgreSQL recognize JSON and JSONB types

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#532]
JSON and JSONB are very common types in PostgreSQL, but they are not recognized by Speedment. The JDBC driver seems to return them as `String`, so it should be easy to add a default mapping [similar to how we map](https://github.com/speedment/speedment/blob/ebd27fe323f329b8f626d74fbb5ae0e567a745a7/runtime-parent/runtime-core/src/main/java/com/speedment/runtime/core/internal/db/postgresql/PostgresqlDbmsMetadataHandler.java#L40) `bytea` to `Blob` in `PostgresqlDbmsMetadataHandler`.

**Comment by minborg** [comment]
Partially fixed via #573
