### ISSUE TITLE
Tool: GUI Database credentials updates do not make it to connection logic

### ISSUE THREAD

**Issue by lawesson** [speedment/speedment#536]
Steps to reproduce:

1. Start tool, attempt to connect with misspelled user name. Connection fails as expected.

2. Update GUI credentials to correctly spelled user name. Connection still fails with a stack trace complaining about misspelled user name from item 1 above. 

Expected behaviour:

The second connection attempt should use the user name from the dialog and therefore work.

**Comment by lawesson** [comment]
The pushed fix solves the problem with a one liner that clearly does not create any regressions. However, a proper fix should probably adress the underlying problem: 

When making a connect attempt, a new dbms child is added to the config document. When that happens, any already present siblings with the same database type should probably be removed.

**Comment by Pyknic** [comment]
Yes. The entire connection process is very messy. This can be seen in `ConfigFileHelper:186` where some of all the issues with it is written in a comment.

**Comment by lawesson** [comment]
I agree and I have read that comment. What I intended to add to that comment is the problem of several similar dbms nodes in the configuration tree. Since the connection logic searches for the dbms node it finds the wrong one when there are several similar ones in the tree. This problem is not covered in the comment you refer to.

Clearly, a refactoring of the connection process seems due and is of course likely to solve also this problem, but if there is a simple fix for the duplicate dbms nodes (I honestly cannot tell) that solution may be useful to implement while waiting for the refactoring.
