### ISSUE TITLE
RDS

### ISSUE THREAD

**Issue by braghome** [speedment/speedment#540]
Any plans of making speedment work over Amazon RDS?

**Comment by minborg** [comment]
@braghome Thank you for you proposal! This would certainly be a good feature. We support PostgreSQL, MySQL and MariaDB and these are some of the engines supported by RDS. 

Is this something you could have a look at @braghome ? What is needed over the current support for PostgreSQL, MySQL and MariaDB? What features would you like to see?

**Comment by Pyknic** [comment]
This feature is considered supported since Amazon RDS and Google Cloud SQL doesn't differ that much from regular MySQL, PostgreSQL etc.
