### ISSUE TITLE
sql:BOOL and sql:FLOAT will be mapped wrong by the default mapper

### ISSUE THREAD

**Issue by Martin-H2** [speedment/speedment#553]
the default mapper assigns
sql:BOOL to java:Integer
sql:FLOAT to java:Double

this may induce the need of unnecessary casting, if the mappings are not corrected in the json config / UI

**Comment by Pyknic** [comment]
Hi! The default mapping is depending on the `DbmsType`. Which database type do you have? (MariaDB, MySQL, PostgreSQL, etc)

**Comment by minborg** [comment]
I believe they have MySQL

**Comment by Martin-H2** [comment]
yes sorry, its mySQL atm

**Comment by lawesson** [comment]
Actually, the mappings are correct. However, the MySQL names BOOL and FLOAT are a bit misleadning, when having the Java type names in mind.

In MySQL, BOOL is synonym for TINYINT(1) and is therefore mapped to an Integer. To get an actual boolean value, please consider using BIT instead. See https://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html

FLOAT is a floating point number with a precision that may exceed what is representable in a Java float. Therefore, the Java mapping is Double. Please consider using REAL for lower precision floating point numbers corresponding to Java float. See https://docs.oracle.com/javase/1.5.0/docs/guide/jdbc/getstart/mapping.html (under 8.3.10	FLOAT)
