### ISSUE TITLE
Tool: Add dialog for entering mandatory settings

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#556]
The "company" setting is best set using a mandatory dialog after metadata is read from the database. Some other settings could also be shown in this dialog.

**Comment by Pyknic** [comment]
I disagree. We want to be able to get to the "Generate Code" with as few clicks as possible. Many first time users don't care what package name they get, and if they care, they have invested enough time for it to feel okay to go back and change. Adding an extra step for every first time user will make the tool feel slower to work with.
