### ISSUE TITLE
PosgreSQL: Streaming resultset does not work

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#568]
Cursor based ResultSet does not seem to work despite #565 being fixed

**Comment by lawesson** [comment]
I cannot reproduce this problem. I have created a database with half a million film records, running this:
 
´´´java
try {
            films.stream().forEach(f -> {
                System.out.println(f);
                throw new RuntimeException("done!");
            });
            throw new IllegalStateException("was supposed to die before coming here!");
        } catch (RuntimeException r) {
            // quite what we expect.
        } 
```

finishes in 20ms when speedment is built with 

```
statement.setFetchSize(FETCH_SIZE)
```

and it takes 2000ms without that setting. This seems to indicate that the cursor based result set does indeed work.

**Comment by lawesson** [comment]
Closing - unable to reproduce
