### ISSUE TITLE
Speedment failing to UPDATE rows

### ISSUE THREAD

**Issue by Nazaire** [speedment/speedment#572]
### JAVA
```
manager.stream()
    .filter(GroupRules.GROUP_ID.equal(group))
    .filter(GroupRules.GROUP_RULE_ID.equal(groupRuleId))
    .map(GroupRules.SRC_NOT.setTo("X"))
    .forEach(manager.updater());
```

### DEBUG
`UPDATE "public"."group_rules" SET "group_id" = ?,"group_rule_id" = ?,"src_id" = ?,"src_not" = ?,"dst_id" = ?,"dst_not" = ?,"rule_id" = ?,"active" = ?,"class" = ?,"comment" = ?,"order_id" = ? WHERE "group_id" = ? AND "src_id" = ? AND "src_not" = ? AND "dst_id" = ? AND "dst_not" = ? AND "rule_id" = ?, values:[8, 1, 5, X, 3, N, 18, Y, null, General Rules, 1, 8, 5, X, 3, N, 18]`

### ISSUE
Speedment is generating this statement, when I am trying to change value **"src_not"** to **"X"**. It is including the **"src_not"** column in the WHERE clause, when that's the column I'm actually trying to change.

Speedment version = 3.0.16
Postgresql runtime = 42.0.0
PSQL Version = PostgreSQL 9.5.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16), 64-bit

Hope this helps. Cheers.

**Comment by minborg** [comment]
It is a semantic definition if this is an error or not. In Speedment, an entity is the same if its primary keys are the same. It appears like the class `GroupRules` does not have any primary keys so Speedment will fall back to using all columns. This works well for `DELETE` but not for `UPDATE` as you rightfully point out. 

As a work around, you could remove the old `GroupRules` and insert the new `GroupRules`. 

It would be possible to change this behavior once #257 is fixed.

**Comment by Nazaire** [comment]
Thanks for getting back to me.

Using your advice this is how I worked around the bug (In case anyone else is interested)

```
manager.stream()
    .filter(GroupRules.GROUP_ID.equal(group))
    .filter(GroupRules.GROUP_RULE_ID.equal(groupRuleId))
    .forEach(g -> {
        manager.remove(g); // REMOVE

        g.setSrcNot("X"); // MAKE CHANGE

        manager.persist(g); // ADD IT BACK
    });
```

**Comment by minborg** [comment]
@Nazaire Thank you for sharing. We will revisit this issue once #257 is fixed.
