### ISSUE TITLE
MariaDB Default Encoding is utf8mb4

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#574]
But we assume it to be utf8 unless two flags are set on init. This can be quite confusing for new users since it looks like it doesn't work unless you change stuff from the recommended setup.

```
ApplicationBuilder app = new SakilaApplicationBuilder()
        .withParam("db.mysql.collationName", "utf8mb4_general_ci") // <-- Must be set on MariaDB
        .withParam("db.mysql.binaryCollationName", "utf8mb4_bin") // <-- Must be set on MariaDB
        .build();
```

**Comment by Pyknic** [comment]
Apparently, [this is only relevant](https://mariadb.com/kb/en/library/differences-in-mariadb-in-debian-and-ubuntu/) on Debian

**Comment by minborg** [comment]
I suggest we document that Debian/MariaDB must have this configuration in the manual and then close the issue.

**Comment by minborg** [comment]
Fixed in manual
