### ISSUE TITLE
JsonB in postgres still coming as optional<String>

### ISSUE THREAD

**Issue by muhdkhokhar** [speedment/speedment#592]
Hi,

I have postgres table with column type "Jsonb" but after generating its coming as Options<String>

I thougt it would as a map or other object

Using 3.0.22-SNAPSHOT

**Comment by minborg** [comment]
The JSON will be mapped to a `String`. You would have to apply a JSON parser on the `String` if you want to convert it to a `Map` or other object. If the column is nullable then you will get an `Optional<String>`.

**Comment by muhdkhokhar** [comment]
How I apply JSON parser??

**Comment by minborg** [comment]
What do you want from your parser? A Java Bean or a Map? There are many third party JSON libraries such a GSON that you can use and that provides many options for you.

**Comment by muhdkhokhar** [comment]
https://github.com/speedment/speedment/issues/532

How this is fixed?

**Comment by minborg** [comment]
#532 was fixed so that Speedment could recognize json and jsonb and map them to `String`. Before this fix, they were mapped to `Object`.

**Comment by muhdkhokhar** [comment]
Thx
