### ISSUE TITLE
can I use the Spring @Transactional

### ISSUE THREAD

**Issue by xjr100419** [speedment/speedment#606]
can I use the Spring @Transactional ??

**Comment by minborg** [comment]
Speedment does not support `@Transactional` but supports transactions as described here: https://speedment.github.io/speedment-doc/crud.html#transactions

It would be cool if it did though.  You could write a support method that takes a `Runnable` and does everything in the `run()` method in a transaction.

**Comment by xjr100419** [comment]
ok ths
