### ISSUE TITLE
Better API for streaming over entities

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#614]
The current Speedment API is a bit limited and can sometimes feel a bit heavy. It works well with predicates, but not so nice when doing mapping-operations or when sorting streams. This could be fixed by letting `__Field`-interfaces expose more methods. We can call this the "compute" system.

**Fields are Comparators**
```java
// Instead of:
employees.stream()
    .sorted(Employee.FIRSTNAME.comparator()
        .thenComparing(Employee.LASTNAME.comparator()))

// You can write:
employees.stream()
    .sorted(Employee.FIRSTNAME
        .thenComparing(Employee.LASTNAME))
```

**Fields are Getters**
```java
// Instead of:
salaries.stream()
    .mapToDouble(Salary.SALARY.getter())

// You can write:
salaries.stream()
    .mapToDouble(Salary.SALARY)
```

**Handle NULL-values easily**
```java
// Instead of:
salaries.stream()
    .map(Salary.TO_DATE.getter())
    .mapToLong((OptionalLong optional) -> optional.orElse(0L))

// You can write:
salaries.stream()
    .mapToLong(Salary.TO_DATE.orElse(0))
```

**Perform Mathematical Operations**
```java
// Instead of:
int currentDate = ...;
final OptionalDouble avgAge = employees.stream()
    .mapToInt(Employee.BIRTDATE.getter())
    .map(birthday -> currentDate - birthdate)
    .average();

// You can write:
int currentDate = ...;
final OptionalDouble avgAge = employees.stream()
    .mapToInt(Employee.BIRTDATE.minus(currentDate).negate())
    .average();
```

Of course you can still use all the old methods for backward compatibility sake.

**Comment by minborg** [comment]
We need to support `ComparableField`s too otherwise it is very confusing.

**Comment by minborg** [comment]
It would be nice if we could make `ComparableField` implement `Comparable`.
