### ISSUE TITLE
AbstractApplicationMetadata Hard Coded Meta Information

### ISSUE THREAD

**Issue by ebautista** [speedment/speedment#615]
While investigating how speedment gets the connection string it uses when connecting to the database, I found out that it is not using the speedment.json file but rather uses a file extending from AbstractApplicationMetadata that seems to be a mirror of whatever is in the json file.

This is a problem when I want the database connected to be changeable on the fly.
Its like for actual application should be connecting to a postgresql DB then for integration testing should be connecting to a mariaDB.

I can't seem to find something like this on the documentation.

**Comment by minborg** [comment]
You might try something like this:
```
final SakilaApplication app = new SakilaApplicationBuilder()
            .withPassword("sakila-password")
            .withDbms(FilmManager.IDENTIFIER, dbms -> dbms.mutator().setTypeName("MariaDB"))
            .build();
```
This will change the type name for the database. Let me know if that works for you.

**Comment by ebautista** [comment]
I cannot find something similar to IDENTIFIER on my generated classes. 
Each manager class represents a table right? Does that mean I need to do this for each of the tables on my current schema?

**Comment by minborg** [comment]
Ahh. My bad. The `IDENTIFIER` will be introduced in 3.1 which is not yet released. You could use any column identifier such as `Film.FILM_ID.identifier()` that sits under the same database.

**Comment by minborg** [comment]
You only need to call it once and all Dbms references will be changed.

**Comment by ebautista** [comment]
Thank you for the quick clarification. Will try it out and give you a feedback as soon as I can.

**Comment by ebautista** [comment]
I was able to make it work, thanks for the help.
