### ISSUE TITLE
Wrong field declaration for autogenerated Enum fields

### ISSUE THREAD

**Issue by manulaiko** [speedment/speedment#622]
After generating the classes from the tool, the fields that are mapped to a enum doesn't get generated properly.

The `EnumField.create` method has a different signature that most of the other fields, this makes the generated code to be wrong:

```java
    /**
     * This Field corresponds to the {@link AccountsMessages} field that can be
     * obtained using the {@link AccountsMessages#getToStatus()} method.
     */
    EnumField<AccountsMessages, Byte, MessageStatus> TO_STATUS = EnumField.create(
            Identifier.TO_STATUS,
            AccountsMessages::getToStatus,
            AccountsMessages::setToStatus,
            new MessageStatusMapper(),
            false
    );
```

The correct one would be:

```java
    /**
     * This Field corresponds to the {@link AccountsMessages} field that can be
     * obtained using the {@link AccountsMessages#getToStatus()} method.
     */
    EnumField<AccountsMessages, Byte, MessageStatus> TO_STATUS = EnumField.create(
            Identifier.TO_STATUS,
            AccountsMessages::getToStatus,
            AccountsMessages::setToStatus,
            new MessageStatusMapper(),
            MessageStatus::name,
            MessageStatus::valueOf,
            MessageStatus.class
    );
```

**Comment by minborg** [comment]
Is is possible for you to upload the `speedment.json` file? This file contains all metadata from the database and the GUI settings. That way, we can reproduce the issue.

**Comment by manulaiko** [comment]
Sure.

This is the json file: https://github.com/manulaiko/speedment-test/blob/master/src/main/json/speedment.json
The TypeMappers and enums are here: https://github.com/manulaiko/speedment-test/tree/master/src/main/java/com/manulaiko/kalaazu/persistence/database/mappers
This is a generated class that uses an enum: https://github.com/manulaiko/speedment-test/blob/master/src/main/java/com/manulaiko/kalaazu/persistence/database/entities/accounts_messages/generated/GeneratedAccountsMessages.java

**Comment by Pyknic** [comment]
Try using the [enum-plugin](https://speedment.github.io/speedment-doc/integration.html#enum) to your `pom.xml`, select its `TypeMapper` in the tool and then regenerate. It has a built-in mapper that creates inner enum-types and sets the field appropriately. Internally it does a rewrite of the field declaration when the generator is executed, which is how the extra parameters are set.

If you are interested in seeing how the rewrite works, it is all [in this module](https://github.com/speedment/speedment/tree/master/plugin-parent/enum-generator).

**Comment by Pyknic** [comment]
If you are using Speedment Enterprise, you should use [the enterprise enum plugin](https://speedment.github.io/speedment-doc/enterprise_enums.html#top) since it also generates efficient serialization of the columns.
