### ISSUE TITLE
Add integration test for MySQL 8.0

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#630]

**Comment by lawesson** [comment]
Automatic testing (currently in development) currently fails since the tool bundles MariaDB jdbc driver that takes precedence.

```java.sql.SQLException: Client does not support authentication protocol requested by server. Consider upgrading MariaDB client. plugin was = caching_sha2_password```

**Comment by lawesson** [comment]
Tests added in enterprise. Tests currently fail due to #616.
