### ISSUE TITLE
Split package com.speedment.runtime.core

### ISSUE THREAD

**Issue by manulaiko** [speedment/speedment#650]
`com.speedment.runtime.core` is declared in `runtime.application` and `runtime.core` modules.

The `runtime.application` defines 3 interfaces which are causing the conflict:

 * `com.speedment.runtime.core.ApplicationBuilder`
 * `com.speedment.runtime.core.ApplicationMetadata`
 * `com.speedment.runtime.core.Speedment`

All of them are already available in the `runtime.core` module so it should be safe to delete them.

![screenshot_20180520_194512](https://user-images.githubusercontent.com/8729653/40281857-8962b4bc-5c66-11e8-90a5-5e57a06bfe62.png)

**Comment by minborg** [comment]
Thank you for reporting this. We will have a look at it.

**Comment by minborg** [comment]
Well spotted! The classes were actually not declared in `com.speedment.runtime.application` but they were sneakily added due to erroneously exporting the package `com.speedment.runtime.core` via the maven-bundle-plugin..

**Comment by minborg** [comment]
I have fixed the problem. The fix will be released in Speedment 3.1.2
