### ISSUE TITLE
Joins break when using aliases in model descriptor

### ISSUE THREAD

**Issue by paxbit** [speedment/speedment#654]
Hi,

we use aliases for our generated model classes. When I tried to integrate the new Speedment Join Feature into our existing Speedment application I noticed that using aliases seems to make asserts made by AbstractJoinBuilder fail. 

Please see the readme of the following repository for a more detailed explanation and also for a showcase:
https://github.com/paxbit/speedment-issue-demo

I looked for existing issues on this and found nothing. However maybe #560 is related.

Best,
Paxbit

**Comment by minborg** [comment]
This is an issue solved by #652
