### ISSUE TITLE
Add tests for Speedment streams

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#659]
Currently, we do not cover all variant in the tests. It would be useful to start with a Speedment stream and then map to Long, Int, Double and apply all kinds of intermediary operations and then all terminating operations. The test should assert autoClose and correct results.

**Comment by minborg** [comment]
We also need to add `takeWhile` and `dropWhile` tests.

**Comment by ractoc** [comment]
I'd be happy to look into this, what class / package would be a good starting point to start looking into adding the test methods?

Do we have some form of code coverage reporting in place anywhere that I can look at?

**Comment by minborg** [comment]
This issue was erroneously placed here when it should be in the CI system instead where tests are run for all database types. I will close this issue. Thank you for offering to contribute!

I will open a new ticket for code coverage which is currently out of order.

**Comment by minborg** [comment]
We would be grateful if you could have a look at the `AutoClosingReferenceStream` in the module `runtime-core` and the other `AutoClosing*Stream` classes in the same package. Maybe it would be good to first migrate to JUnit5 for that module.

**Comment by minborg** [comment]
I have migrated to JUnit 5 now and fixed the tests.

**Comment by minborg** [comment]
@ractoc Thanks for helping with how to use mockito and JUnit5
