### ISSUE TITLE
MariaDB: Metadata loading is very slow on remote hosts

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#681]
Loading the Employees-table metadata from a database hosted in the cloud in a zone nearby takes up to a minute. Sometimes this causes the connection to reset. The Employees table is not very large, only a handful of tables, so it should be fast.

**Comment by minborg** [comment]
We recently update retrieval of index metadata so it became faster. We should profile what operation is causing the delay.

**Comment by minborg** [comment]
Here is an example of a MySQL local database
```
2018-12-04T10:32:47.227Z INFO  [ForkJoinPool.commonPool-worker-1] (c.s.r.c.i.d.AbstractDbmsMetadataHandler) - Aggregate duration of metadata retrieval [ms]: Table=29, Index=120, ForeignKey=96, PrimaryKeyColumn=79, Column=930

```

**Comment by lawesson** [comment]
Results for 3.1.9, loading metadata from a cloud Sakila database>

Aggregate duration of metadata retrieval [ms]: ForeignKey=21,459, Table=369, Index=10,816, PrimaryKeyColumn=16,037, Column=20,895
