### ISSUE TITLE
Online Initializer produces broken poms, speedment:tool does not work either

### ISSUE THREAD

**Issue by AtomicStryker** [speedment/speedment#683]
There are *several* issues with using the Initializer to get anything started with speedment.

*1
Go to the online initializer, switch In-memory acceleration to off so the generate button works.
The generated pom file which can be previewed contains atleast 2 invalid lines:

"<version>${speedment.version}</version>" refers to a variable that does not exist. Only speedment.enterprise.version is defined.

speedment.enterprise.version is set to "1.1.7" if in-memory acceleration is off, this version does not exist on the repository URL. "3.1.3", the version set when in-memory acceleration is on, exists.

*2
Running "mvn speedment:tool" with a fixed pom.xml results in "The expected .json-file '...\speedinit\src\main\json\speedment.json' does not exist."

*3
Creating said json and running the command again results in "Execution default-cli of goal com.speedment:speedment-maven-plugin:3.1.3:tool failed: First argument is null"

**Comment by minborg** [comment]
A very serious issue. We will fix this immediately. Thank you for submitting this.

**Comment by Pyknic** [comment]
@AtomicStryker This should now be fixed. Please let us know if you find any other issues with it.
