### ISSUE TITLE
tableManager.IDENTIFIER returns old schema when using withSchema("test")

### ISSUE THREAD

**Issue by alstomutrecht** [speedment/speedment#684]
When opening a database with another schema using withSchema("test"), the tableManager..IDENTIFIER.asSchemaIdentifier() returns the old schema name i.s.o. "test".

I am using version 3.1.4.

**Comment by minborg** [comment]
Sorry for my late response. The `id` remains the same regardless of `withSchema()' but the `name` changes. It is `name` that is being used when rendering SQL queries. I hope this clarifies the situation.
