### ISSUE TITLE
Speedment shall inhibit logging of thrown SQLExceptions

### ISSUE THREAD

**Issue by lawesson** [speedment/speedment#693]
Exceptions caused by SQLExceptions shall not be logged by Speement if they are thrown to the user. 

For cases of retry, there shall be a LogType.SQL_RETRY such that an application built with withLogging(SQL_RETRY) will log SQL-related exceptions that cause retry. The default behavior is to suppress exceptions from intermittent problems that are later overcome by retrying.

**Comment by minborg** [comment]
This involves changes in `AbstractDbmsOperationHandler::executeNotInTransaction` and `AbstractDbmsOperationHandler::executeInTransaction` to supress retrying exception printout and adding a new enum value in `ApplicationBuilder.LogType` as per comment above.
