### ISSUE TITLE
Custome gererator with Serializable interface

### ISSUE THREAD

**Issue by Shengche** [speedment/speedment#695]
Dear @minborg 

I want to customize code generator for generate Serializable in GenerateTable, do you have any opinion?

**Comment by minborg** [comment]
Sounds like an interesting idea. How do you want your code to look like? Is it enough to just add `implements Serializable` to the class declaration or do you want to generate custom serialization code too?

There is a way of decorating the current code generator so it can add things to a class that has just been generated.

**Comment by Shengche** [comment]
I am using Apache Wicket Framework which object have to serializable , in order to render web page.
I add implementation in generated code manually like below:


/**
 * The main interface for entities of the {@code actiontype}-table in the
 * database.
 * <p>
 * This file is safe to edit. It will not be overwritten by the code generator.
 * 
 * @author 
 */
public interface Actiontype extends GeneratedActiontype, Serializable {}

**Comment by minborg** [comment]
The easiest way to make an entity serializable is to override the code manually exactly as you write above (under the assumption that there are not so many tables). The `Actiontype` is only generated once whereas the `GeneratedActiontype` is regenerated everytime you generate code (e.g. tool and generate targets). 

If you want to add your own decorator, you can do like this outline (it is a bit complicated):

```
public final class MyEntityDecorator
implements TranslatorDecorator<Table, Interface> {

    @Override
    public void apply(JavaClassTranslator<Table, Interface> translator) {
        translator.onMake((file, builder) -> {

        /// Add code here that just adds the "Serializable" interface to the Generated class

        });
    }
}
```
Then add the decorator

```
@InjectKey(MyGeneratorComponentImpl.class)
public final class MyGeneratorComponentImpl {
    
    @ExecuteBefore(RESOLVED)
    void installGenerators(@WithState(INITIALIZED) CodeGenerationComponent codeGen) {
                    codeGen.add(Table.class,   StandardTranslatorKey.GENERATED_ENTITY, new MyEntityDecorator());
    }
}
```
Now that this is done, you need to place the MyGeneratorComponentImpl class so that the speement-plugin picks it up:

```
   <build>
        <plugins>
            <plugin>
                <groupId>com.speedment.enterprise</groupId>
                <artifactId>speedment-enterprise-maven-plugin</artifactId>
                <version>${speedment.version}</version>
                
                <configuration>
                    <components>

                       // Add the custom decorator installation class
                        <component>com.packagename.MyGeneratorComponentImpl</component>
                        
                    </components>
                    <appName>${project.artifactId}</appName>
                    <packageName>${project.groupId}</packageName>
                </configuration>
                
                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>${mysql.version}</version>
                        <scope>runtime</scope>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
```

**Comment by Shengche** [comment]
@minborg , thanks. Let me try.

**Comment by Shengche** [comment]
After few try-errors, finally I got the wanted result.
First, add dependencies:
`
        <dependency>
            <groupId>com.speedment.common</groupId>
            <artifactId>codegen</artifactId>
            <version>2.5.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.speedment.plugins</groupId>
            <artifactId>enum-generator</artifactId>
            <version>${speedment.version}</version>
        </dependency>

        <dependency>
            <groupId>com.speedment.generator</groupId>
            <artifactId>generator-translator</artifactId>
            <version>${speedment.version}</version>
`
