### ISSUE TITLE
Update JDBC Drivers to latest version

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#702]
MySQL 8.0.13
PostgreSQL 42.2.5

**Comment by minborg** [comment]
The MySQL version is a step from 5.x to 8.x so we need to check carefully. Also, the manual has to be updated.

**Comment by lawesson** [comment]
Initializer updated, tabula rasa tests passed for all database engines, jdk8 and initializer jdk8. Also tested downloading mysql initializer zip file for both java8 and java11, ran tool, generate and a simplistic creation of a stream.
