### ISSUE TITLE
Selective INSERT does not return DEFALUTed field values

### ISSUE THREAD

**Issue by lawesson** [speedment/speedment#710]
When persisting an entity, Speedment will return a possibly updated entity. Using selective persistence, the user may select to omit some fields from the operation and let the database fill them in. The returned entity will then have the omitted fields set to the values now present in the database. See https://speedment.github.io/speedment-doc/crud.html#selecting-fields-to-persist

This works for example for an autoincrementing ID field where persisting the entity with the ID field omitted will return an entity with the ID set to the generated value in the database.

It does _not_ work for DEFAULT values in the database, however. For those values, the field will not be updated. JDBC does not seem to return any values at the time of persistence here, but the default values are available via JDBC metadata.

Solving this problem would allow for more efficient Hazelcast persistence. The easiest solution is probably just to document this bevaviour.

**Comment by minborg** [comment]
Documented
