### ISSUE TITLE
Introduce "alias" for schemas, tables and columns

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#72]
The "alias" is used for the Java code domain whereas the existing "name" is used for the database domain. 

For example, a database table name is "RGN" and we want to keep it that way except that we in the code would like to reference it as Region. So regions.stream() would for example return a stream of Region obtained from the RGN table. Same goes for columns and schemas too, where we might have a column "avg" but we can use Region::getAverage instead.

**Comment by Pyknic** [comment]
This is now fixed.
