### ISSUE TITLE
Can speedment be used as one instance through-out an application?

### ISSUE THREAD

**Issue by sayonara44** [speedment/speedment#734]
Hello, not sure if this is the right place or not. But I took interest in finding and trying out Speedment and I really like the framework. I was previously using JDBI with Hikari and creating one instance of JDBI after the configuration, at the start of my game server and then using it through-out my application. 

My application is a multi-player game that allows users to make characters do various things (level up, gain stats, quests). Character data will be loaded upon logging in and entering game and then be saved once a player logs-out or changes session in real-time. So when the player wants to get back in-game, everything they had before they logged out will still be there. The game server will most likely be always on, while allowing players to connect to it simultaneously. (Its a server -> client game based on Netty's IO networking).

So with that being said, is it safe to create an instance of my speedment application like

```
public final class Database {

private static Database instance;
private Application app;

 private Database() {
      app = new ApplicationBuilder().withUsername(username)
            .withPassword(password)
            .withSchema(schema)
            .build();
 }

  public static void init() { instance = new Databse(); }

  public static Application app() { 
       return instance.app;
  }
}`
```

And then when I start my servers I would just call the init() to set up the Speedment application. 
Then freely use it as so:

```
AccountsManager acc = Database.app().getOrThrow(AccountsManager.class);
// .. do work

CharactersManager chrs = Database.app().getOrThrow(CharactersManager.class);

// .. do work
```

Is this safe to do? I know that in the examples from wiki, I always see app.close() after work has been done. But in my case I need to be able to access the DB whenever characters login/out or do various things. So would i have to manually close the connection after each use? If so how would I go about doing that and how would I be able to manage my connection pooling as I did so before using HikariCP? I don't want the db to hog all the memory as my game relies on it as well.

Thanks for reading thus far, if you have any concerns or require additional information please let me know. Also again I do apologize if this isn't the right section to post this. I couldn't find a common support page for Speedment. If it is then please let me know and i'll be able to move this post to whatever support section is available. 

Oh and i'm just a sole developer using the open-source version of Speedment~

Thanks again.

**Comment by minborg** [comment]
Hi @sayonara44 

Speedment will manage all DB connections and connection pooling for you so you do not have to worry about that. If you forget to close you `Speedment` instance after use, it will not affect data stored in the database.

That said, you could add a static method to your singleton `Database` class named `shutdown()` or similar that closes Speedment properly when you exit your code.

**Comment by minborg** [comment]
Please consider closing this issue if you are happy with the answers given.
