### ISSUE TITLE
Example for integrating Speedment with dropwizard framework.

### ISSUE THREAD

**Issue by komalbb** [speedment/speedment#738]
How to integrate Speedment in Dropwizard framework? Can someone point me an example?

**Comment by minborg** [comment]
Do you have an example of dropwizard that shows an intended use?

**Comment by komalbb** [comment]
@minborg , This is my example project, https://howtodoinjava.com/dropwizard/tutorial-and-hello-world-example/ . On the database entities, I want to use the Speedment to fetch the result data, instead of sql queries.

**Comment by minborg** [comment]
ok. I think it would be fairly easy to use Speedment. Create a database table "employee" with columns id, first_name, last_name and email. Use the Speedment initializer to create a `pom.xml` file and then copy relevant parts from that `pom.xml` file to your dropwizard project. Run the Speedment tool that generates all database classes for you.

Add Speedment code and inject Speedment managers in your rest controller.

 For example:

```
    @GET
    @Path("/{id}")
    public Response getEmployeeById(@PathParam("id") Integer id) {
        Employee employee = EmployeeDB.getEmployee(id);
        if (employee != null)
            return Response.ok(employee).build();
        else
            return Response.status(Status.NOT_FOUND).build();
    }
```
would instead be:

```
    @GET
    @Path("/{id}")
    public Response getEmployeeById(@PathParam("id") Integer id) {
        Optional<Employee> emp = employees.stream().filter(Employee.ID.equal(id)).findAny();
        if (employee.isPresent())
            return Response.ok(employee.get()).build();
        else
            return Response.status(Status.NOT_FOUND).build();
    }
```

**Comment by komalbb** [comment]
@minborg  I already have the database classes in my code. How the manager classes are  been generated. what is the equivalent in Dropwizard for this command. app.getOrThrow(EmployeeDB).
In the above example, how is the employees been created?

**Comment by minborg** [comment]
I think the best way is to create a stand-alone Speedment project for the database you already have to learn more on how Speedment works. The Speedment instance and the EmployeeManager are created just once like in this example (for another project but the same principle):

https://speedment.github.io/speedment-doc/getting_started.html#hello-world

If you are uncertain how to use dependency injection you can always create a singleton class and retrieve your EmployeeManager from there.

**Comment by komalbb** [comment]
@minborg  Will try the stand-alone project.
