### ISSUE TITLE
How can I add a default where clause in the stream?

### ISSUE THREAD

**Issue by solangepaz** [speedment/speedment#739]
I wanted to add a where clause whenever a stream is made, but I do not know if this is possible. If so, how can I do it? The aim would be to change in the speedment base code.
For example, if I do this stream:
```
LineitemManager lineitem = app.getOrThrow (LineitemManager.class);
         DoubleSummaryStatistics intsum = lineitem
                 .stream ()
                 .filter (Lineitem.L_SHIPDATE.greaterOrEqual (sqlDate)); (....)
```

He should return the result of:
```
LineitemManager lineitem = app.getOrThrow (LineitemManager.class);
         DoubleSummaryStatistics intsum = lineitem
                 .stream ()
                 .filter (Lineitem.L_SHIPDATE.greaterOrEqual (sqlDate))
                 .filter (Lineitem.L_DISCOUNT.lessThan (1.2)); (...)
```

**Comment by minborg** [comment]
You could always add a custom method in `LineitemManager` that does this. For example:

```
   Stream<LineItem> myStream() {
        return stream().filter(Lineitem.L_DISCOUNT.lessThan (1.2));
   }
```

**Comment by minborg** [comment]
You can also write your own "MyLineitemManager extends LineitemManager" that overrides `stream()` and applies an extra filter. This class is then injected in the `ApplicationBuilder` and will replace the generated one.

**Comment by solangepaz** [comment]
Thank you :)
