### ISSUE TITLE
Create a HasColumn.findColumnOrThrow()

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#743]
The trait `HasColumn` has a method `findColumn()` which returns an `Optional`, but it is very common that the only thing we do is to call `Optional.get()`. If the key does not have any corresponding column, this indicates a problem with the metadata, but it can be very hard to find which table and column the problem is about without any more details. By introducing a method `findColumnOrThrow()` we can throw a descriptive exception about which table is referencing which column to make these errors easier to debug. We should also probably scan the entire codebase for `.findColumn().get()` and make sure we use the new method instead.

**Comment by DNAlchemist** [comment]
Sounds good.
I think the method name `getColumn` will be obvious enough.
