### ISSUE TITLE
Check size calculations for class in GUI

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#76]
Dec 04, 2015 10:15:10 AM com.sun.javafx.scene.control.skin.VirtualFlow addTrailingCells
INFO: index exceeds maxCellCount. Check size calculations for class com.speedment.internal.newgui.ProjectTreeController$1

**Comment by Pyknic** [comment]
I can't reproduce this message. Has anyone else encountered this?

**Comment by Pyknic** [comment]
I am closing this issue since we haven't encountered this again.
