### ISSUE TITLE
Tool: JavaFx Exception when launching the tool

### ISSUE THREAD

**Issue by julgus** [speedment/speedment#765]
When launching the tool to regenerate code, Speedment 3.1.17 casts the following Exception:

`aug. 29, 2019 4:53:49 EM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
INFO: Could not load @font-face font [jar:file:/Users/juliagustafsson/.m2/repository/com/speedment/enterprise/enterprise-tool/3.1.16/enterprise-tool-3.1.16.jar!/fonts/SourceCodePro-Regular.otf]
aug. 29, 2019 4:53:49 EM javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @38ed139b)' while converting value for '-fx-background-color' from rule '*.menu-bar' in stylesheet jar:file:/Users/juliagustafsson/.m2/repository/com/speedment/enterprise/enterprise-tool/3.1.16/enterprise-tool-3.1.16.jar!/css/enterprise.css
aug. 29, 2019 4:53:49 EM javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @38ed139b)' while converting value for '-fx-background-color' from rule '*.menu-bar *.menu' in stylesheet jar:file:/Users/juliagustafsson/.m2/repository/com/speedment/enterprise/enterprise-tool/3.1.16/enterprise-tool-3.1.16.jar!/css/enterprise.css
aug. 29, 2019 4:53:50 EM javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @38ed139b)' while converting value for '-fx-background-color' from rule '*.menu-bar *.menu' in stylesheet jar:file:/Users/juliagustafsson/.m2/repository/com/speedment/enterprise/enterprise-tool/3.1.16/enterprise-tool-3.1.16.jar!/css/enterprise.css
`

**Comment by dekmm** [comment]
Is there a specific way to recreate this? I can't get it to reproduce the exception locally.

**Comment by julgus** [comment]
I ran into this error immediately upon launching Speedment. I'll try to run it again and see if it is still an issue.

**Comment by julgus** [comment]
I realize now that this was probably resolved with release 3.1.17. I must have ran on 3.1.16 unintentionally.
