### ISSUE TITLE
Tool: Unable to disable all columns

### ISSUE THREAD

**Issue by julgus** [speedment/speedment#766]
The context menu in the tool does not work as intended for the following reasons:

- In some cases it is not available for display at all (nothing happens when right clicking in the tree). 
- If the context menu appears, the option "Disable all columns" often fails to have any action. I say often since I got it to work a few times with a similar setup earlier today for the same Speedment version. 
- If a table is disabled, all its columns are still marked as "enabled". If a table is disabled, there should at least be an indication that the columns will not be imported as well. 

The logs does not give any indications of what might cause this behavior. 

I'm running on Speedment 3.1.17.

**Comment by dekmm** [comment]
I've tested the tool on versions 3.1.18 and 3.1.19-SNAPSHOT and the first 2 issues don't seem to exist anymore. On the other hand, the third issue is still prevalent.

**Comment by minborg** [comment]
I think that if a table is disabled, the columns should remain in their enable/disable state. However, the column shall be rendered in another way in the GUI. This means that one can disable a table but still keep the original disable/enable state for columns.

**Comment by minborg** [comment]
This should also be true for the PK and indexes.

**Comment by minborg** [comment]
so in terms of rendering, `indicatedEnabled = column.isEnabled() && column.parent().isEnabled()`

**Comment by dekmm** [comment]
Sounds good, I'll make the changes soon
