### ISSUE TITLE
Update initializer to work with modules

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#786]
The following lines must be added to the `pom.xml` to be able to run under the module system:

```
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
            </plugin>
```

We could also add comments in the Main file:
```
// If you want to run under the Java Platform Module System (JPMS), add a
// "requires com.speedment.runtime.application" in your "module-info.java" file
```
```

**Comment by julgus** [comment]
Should the module system be default or should it be an option in the initializer to run without the module system?

**Comment by minborg** [comment]
Good question. The best thing would be a radio button with "Use Java Module System" and then we could generate a template `module-info.java` file and add the `maven-compiler-plugin` in the `pom.xml`. 

Second best (and presumably easier): Always adding the `maven-compiler-plugin` would be ok (does not harm if JPMS is NOT used) and having comments as proposed could guide the user to implement her own `module-info.java` file.

**Comment by minborg** [comment]
Having a check box would highlight that Speedment is JPMS capable.

**Comment by minborg** [comment]
Here is the new logic for the `pom.xml` file: Unconditionally add the following section under `<build><plugins>`:

```
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
            </plugin>

```

If the module system is selected, a new file `module-info.java` shall be added in the directory `src/main/java` whereby the contents shall look like this:

```
module $ArtifactId {
    requires com.speedment.runtime.application;
    requires com.speedment.enterprise.datastore.runtime; // If $DataStore.enable
    requires com.speedment.enterprise.plugins.enums; // if $Plugins.enums
    requires com.speedment.enterprise.plugins.json; // if$Plugins.JSON

    // If $Plugins.spring (all of the below)
    requires com.speedment.enterprise.plugins.spring.runtime;
    requires spring.boot;
    requires spring.web;

    requires java.annotation;
    requires spring.webmvc;
    requires spring.beans;
    requires spring.context;
    requires spring.core;
    requires spring.boot.autoconfigure;
}
```
Where:
`$ArtifactId` is the specified "ArtifactId" in the initializer
`$DataStore.enable` is the specified check box in the initializer
etc.

**Comment by minborg** [comment]
all the database modules and `join` have been broken out as separate modules now. So the `module-info` should look like this:
```
module mymodule {
    requires com.speedment.runtime.application;
    requires com.speedment.runtime.connector.mysql; // Depending on which DB was selected
    requires com.speedment.runtime.join; // Always add this. Could be removed if joins are not used
}
```

The generator automatically includes all open db:s so the POM remains the same.

The `Main` file needs to be expanded:
```
.withBundle(JoinBundle.class)
```

**Comment by julgus** [comment]
I've updated the initializer and the generator to accomodate the new module system. It is ready for launch as soon as the JPMS feature is completed.
