### ISSUE TITLE
Generated code is too tied to the specific database instance

### ISSUE THREAD

**Issue by anton-johansson** [speedment/speedment#8]
I think the generated code is a little too tied to the specific database instance, instead of just the database schema. I mean, the code is representing the schema after all, not the actual database.

When starting my application, I do not specify which server or which database to use. The only reference I can find for "127.0.0.1" is within the generated metadata, so I assume that's what it uses when it connects to the database.

I'd like to see something like this:
```
new SpeedmentApplication()
	.server("127.0.0.1")
	.database("SpeedmentTest")
	.withUsername("root")
	.withPassword("X")
	.start();
```

If you want to have multiple instances running for your system (for example for different customers) that use the same database schema, you don't want to generate code for each server/database.

**Comment by minborg** [comment]
Good suggestion. We need to somehow make a generic builder pattern for the entire metadata tree.

**Comment by minborg** [comment]
I have started with this issue now. There will be methods similar to the one Anton suggested and also additional generic "with()" methods that can take any type of config node.
