### ISSUE TITLE
Can't extract module name from runtime-3.2.0-SNAPSHOT.pom:

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#801]
the following warning is printed "Can't extract module name from runtime-3.2.0-SNAPSHOT.pom: zip END header not found"

This pom is just a pom-wrapper for other pom:s and is not a java module.

**Comment by minborg** [comment]
The module name can be set explicitly:

```
```

**Comment by dekmm** [comment]
Can't reproduce this anymore, I'll consider it fixed.
