### ISSUE TITLE
Multi tenant support

### ISSUE THREAD

**Issue by manikantag** [speedment/speedment#81]
Hi,

In these cloud era days, multi tenancy is gained much more traction. In fact in our current projects, we are using schema per tenant & column based designator approach.

Is there any plan to support this? Thanks.

**Comment by minborg** [comment]
Started on this issue. There will be a new <pre>public T withSchema(final String schemaName)</pre> method that allows selection of schema when the application starts.

**Comment by minborg** [comment]
Multi-tenant support can be done like this:
<pre>
speedment = new HaresApplication()
    .withUser("tenant-1234-user")
    .withPassword("tenant-1234-pw")
    .withSchema("tenant-1234-schema-name").build();
</pre>

Will be included in the next release!
