### ISSUE TITLE
build fails at runtime-application

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#821]
`mvn clean install -Prelease` fails at `runtime-application`.

It is possible to continue with `mvn clean install -Prelease -rf :runtime-application` and then it works (sic1).

**Comment by minborg** [comment]
This is because 
```
/Users/pemi/git/speedment/speedment/runtime-parent/runtime-join/target/runtime-join-3.2.6-SNAPSHOT.jar:/Users/pemi/git/speedment/speedment/runtime-parent/runtime-connector-parent/mysql/target/connector-mysql-3.2.6-SNAPSHOT.jar:/Users/pemi/git/speedment/speedment/runtime-parent/runtime-connector-parent/mariadb/target/connector-mariadb-3.2.6-SNAPSHOT.jar:/Users/pemi/git/speedment/speedment/runtime-parent/runtime-connector-parent/postgres/target/connector-postgres-3.2.6-SNAPSHOT.jar:/Users/pemi/git/speedment/speedment/runtime-parent/runtime-connector-parent/sqlite/target/connector-sqlite-3.2.6-SNAPSHOT.jar'
```
ends up in the `--class-path` and not the `--module-path`

**Comment by minborg** [comment]
Reproduce: `cd runtime-parent; mvn clean install -Prelease`

Checkout the `runtime-application/target/apidocs` options and argfiles

**Comment by dekmm** [comment]
This doesn't seem to be an issue anymore. After running `mvn clean install -Prelease` the project had built successfully.

Closing for now.
