### ISSUE TITLE
tool: FK not shown as disabled

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#827]
Reproduce: Select schema and then right click and select "Disable All Tables". Expand a disabled table and the fk are not shown as disabled.
<img width="312" alt="Screen Shot 2019-11-15 at 10 35 35 AM" src="https://user-images.githubusercontent.com/7457876/68933020-13fb1e00-0794-11ea-9d69-ad599046fb81.png">

**Comment by julgus** [comment]
Won't fix.
