### ISSUE TITLE
connection pool

### ISSUE THREAD

**Issue by nitincchauhan** [speedment/speedment#85]
speedment supports jdbc connection pool (HikariCP/jdbc-pool) ? will appreciate example.

**Comment by minborg** [comment]
Speedment has a built-in default connection pool (ConnectionPoolComponentImpl). That connection pool is used by default. You can, in principle, plug in any connection pool if you wrap it in a ConnectionPoolComponent. I can help you out if you want to plug in HikariCP. Go to https://gitter.im/speedment/speedment and we can talk more there.

**Comment by nitincchauhan** [comment]
I think there is no one to talk to at Glitter (at this time)
It is probably better for speedment to focus and do things it does best.
having worked on one I know pool in itself is complex component.
speedment should 'use' existing pools unless ConnectionPoolComponentImpl has something that does not exist elsewhere.
