### ISSUE TITLE
SpeedmentPredicated combine issue

### ISSUE THREAD

**Issue by Shengche** [speedment/speedment#852]
Dears

I wrote a function to filter result with speedment 3.2.5

SpeedmentPredicate<PhotoInfoView> predicate = PhotoInfoView.UPLOADED.between(start, end);
predicate.and(PhotoInfoView.COUNTY.equal(AcUtils.CHCOUNTY));

and the logger showed it only filter with PhotoInfoView.UPLOADED.between(start, end)

finally, I changed to using List<SpeedmentPredicate<PhotoInfoView>> speedmentPredicateList = new ArrayList<>();

speedmentPredicateList.add(PhotoInfoView.UPLOADED.between(start, end));
 speedmentPredicateList.add(PhotoInfoView.COUNTY.equal(AcUtils.CHCOUNTY)
                    .and(PhotoInfoView.CITY.in(AcUtils.CHCITY, AcUtils.FENYUAN, AcUtils.HUATAN)));

and

speedmentPredicateList.stream().reduce(s -> true, SpeedmentPredicate::and)

It works!

Any idea about first use case?
[json.zip](https://github.com/speedment/speedment/files/3992424/json.zip)

**Comment by minborg** [comment]
So, the thing here is that `and` returns a *new* predicate that is the combination of the two predicates.

```
SpeedmentPredicate<PhotoInfoView> predicate = PhotoInfoView.UPLOADED.between(start, end)
  .and(PhotoInfoView.COUNTY.equal(AcUtils.CHCOUNTY));
```

**Comment by Shengche** [comment]
So it is .....

Thank you @minborg
