### ISSUE TITLE
Add interface/trait ability to tables/columns

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#864]
Add the ability to add custom interfaces and traits for tables and columns. 

Table: A list of provided interface names are added to what the generated class implements. The classes are not generated but is expected to be provided through user code.

Column: A list of provided trait interfaces are used by the code generator to generate such traits with the set of getters and setters that are common for a particular trait.

**Comment by minborg** [comment]
Column: So if two columns `foo` and `bar` have the same trait called `Baz` then there will be an interface under project_root.trait.Baz that contains the methods `setFoo`, `getFoo`, `setBar` and `getBar` respectively. All table entitites that has the `Baz` trait will implement this trait.

**Comment by minborg** [comment]
I suggest that we only do the Table feature.

**Comment by dekmm** [comment]
Added support for custom entity interfaces
