### ISSUE TITLE
Improve JsonEncoder efficiency

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#87]

**Comment by Pyknic** [comment]
The performance is really bad compared to for an example Gson. We might want to change to that system if we are going to use this in for an example a REST API.

**Comment by anton-johansson** [comment]
I may be completely out of it here, but should Speedment really handle JSON? I guess there could exist a plug-in that adds toJson() methods to each entity, but it feels strange that the Speedment core would handle this. Not sure which component you use for JSON, but if you would use Gson for example, I see two issues:
  * The Speedment dependency tree gets bloated
  * People might have some other (incompatible) version of Gson

**Comment by Pyknic** [comment]
That is a good point. The reason we added our homegrown toJson() was that we found that many new users spent more time on formatting their JSON output than they did learning the framework. This was the cast for the [Build a Social Network tutorial](https://github.com/speedment/speedment/wiki/Tutorial:-Build-a-Social-Network) for an example.

We could just drop the toJson()-method and let the user use Gson or any other library instead. That would clean up the generated entity classes a bit. A problem I see with this however is that you often want to manipulate certain fields before sending them. In _Social Network_ for an example we have the "password" column in the database that we don't want to expose. We also need to inline certain elements retrieved using foreign keys. If we use Gson we would have to create temporary classes for serialization to control the structure of the output.

**Comment by anton-johansson** [comment]
Yeah, I've seen it. I understand that it's easier to get started with Speedment if things like this exist, but it's not a good enough reason in my point of view. :)

Hmm, true, there are some issues with that. But how about my other suggestion? Using a Speedment plug-in for this? A plug-in that simply adds the ```#toJson()``` method, just like it's done today. Then you would only need a dependency on Gson (for example) if you want to utilize that plug-in. This plug-in could be used for in your Social Network tutorial.

**Comment by Pyknic** [comment]
I think the best solution for this is to remove this from the runtime module in 2.4.0 Forest and instead supply a plugin that enables you to parse entities into JSON.

**Comment by Pyknic** [comment]
This is now fixed in branch `develop-modules`.
