### ISSUE TITLE
how i can use command generate code from database?

### ISSUE THREAD

**Issue by ming15** [speedment/speedment#90]
if i dont want to use gui to generate my code, so can i use maven command or other ways??

in [speedment](https://github.com/speedment/speedment) this page, i read ` you can change the way code is generated using an intuitive GUI or programatically using your own code.`, it says `programatically using your own code`, how???

**Comment by minborg** [comment]
There is a target named speedment:generate that you can use. That requires that you have an existing groovy file. So, start with the speedment:gui target just once to create the file, and then you can run without gui.  You can also create the groovy file by hand but that is rather difficult.

Here is an example of a groovy configuration file: https://github.com/speedment/speedment-code-samples/blob/master/hares/src/main/groovy/speedment.groovy
