### ISSUE TITLE
Add possibility to configure metadata model via maven

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#91]
```xml
<plugin>
	<groupId>com.speedment</groupId>
	<artifactId>speedment-maven-plugin</artifactId>
	<version>${speedment.version}</version>
	<configuration>
		<server>${speedment.databaseServer}</server>
		<schema>${speedment.databaseSchema}</schema>
		<user>${speedment.databaseUser}</user>
		<password>${speedment.databasePassword}</password>
	</configuration>
</plugin>
```

**Comment by orwashere** [comment]
How does the generate mojo supposed to behave for this issue? I mean currently it seems generate mojo looks for the configuration file and makes the generation based on the information there. No actual database connection is made to retrieve fresh db state. How should it behave if we provide the config via maven? Connect to the database and make the config file generation from scratch?

**Comment by anton-johansson** [comment]
Well, currently there are two goals:
  * generate
  * gui

Generate, as you mention, only seem to generate code from a confuguration file.
GUI opens up the GUI where you can update your config.

IMO, there should be a way to update the configuration file from the maven-plugin as well. Either through the generate goal, or through a new goal. But preferably the generate goal. :)

I'd like to avoid using the GUI as much as possible. If I add a new table to my database, I'd like my build-process to automatically generate the new sources. Of course, if I need to modify anything (such as mapping between column & java field) I need to either use the GUI or manually editing my configuration file.

**Comment by anton-johansson** [comment]
> Connect to the database and make the config file generation from scratch?

I guess that things that the configuration file already has should be kept. But for new tables and columns, default settings should be generated.

**Comment by Pyknic** [comment]
Perhaps we could mark overwritable values in the config file somehow. Then the generator could replace those with new values from the database but keep all the others. I am not sure of a good way of doing this in JSON other than naming them in a different way (underscore at the end of the key to signify a default-generated value for an example). A default generated value would always be overridden by a custom one.

Another solution would be to have two .json files. One that is always replaced and one that is only added to, never overwritten. The generator will take the first model, replace fields with custom declarations from the second one and then apply it.

**Comment by Pyknic** [comment]
Database username, password, host and port can now be set using either the pom parameters...
```xml
<dbms.host>127.0.0.1</dbms.host>
<dbms.port>3306</dbms.port>
<dbms.username>root</dbms.username>
<dbms.password>password</dbms.password>
```

...or by specifying the same on the command line when running the maven goal:

```
mvn speedment:reload -Ddbms.username=root -Ddbms.password=password
```

Dbms and Schema is taken from the configuration file or through the tool, I do not really see the need for connecting to a database without either config file or tool. That would just reinvent the config file inside the pom.
