### ISSUE TITLE
Static imports in CodeGen with the same package name are filtered away

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#95]

**Comment by Pyknic** [comment]
When the following code is generated with CodeGen and AutoImports is used, you may ant to static import "Bar.bar", but since it is located in the same package it is removed by codegen. The generated code will therefore be erroneous.

```java
public class Foo {
    public static void main(String... param) {
        System.out.println(bar()); // Static import.
    }
}

class Bar {
    public static String bar() {
        return "bar";
    }
}
```
