### ISSUE TITLE
Move class TriConsumer into package com.speedment.runtime.core.db

### ISSUE THREAD

**Issue by ysyim** [speedment/speedment#992]
Hi, @minborg 

**Issue Description**

Package **_com.speedment.common.function_** are a promiscuous package, and groups together miscellaneous functionalities that might be useful to different subsystems. The package structure violates the “high cohesion and low coupling” design rules. I found that Class **_TriConsumer_** is not used by classes in their package. The project has grown larger, leading to becoming increasingly hard to maintain. For example, if one modifies package **_com.speedment.common.function_** (i.e., package rename), and forget to change class **_SqlTriConsumer_** during the maintenance process, there are indirect consequences for the class **_SqlTriConsumer_**. 

Location: The source file can be found at path File 
common-parent/function/src/main/java/com/speedment/common/function/TriConsumer.java

**Refactoring suggestions**

I suggest to move class **_TriConsumer_** into package **_com.speedment.runtime.core.db_**.

<img width="900" alt="speedment-TriConsumer-java" src="https://user-images.githubusercontent.com/104186731/165086339-8849a1bf-13e5-4e92-8955-51727e2b3e76.png">

**Comment by minborg** [comment]
I think in principle, you are right. However, moving this now would break API compatibility. There might be code not in the open-source library that is using this interface. In fact, I know there are other libraries that do precisely this.

The idea from the beginning was to expand the existing `java.util.function` functional interfaces and to keep them all in a single place.

**Comment by minborg** [comment]
Closing this issue. Please reopen if more arguments arrive.
